from prophet import Prophet
import pandas as pd
import random
import numpy as np
import pickle, os

def predict_soil_moisture(history_df):
    # simple Prophet forecast wrapper (keeps original behavior)
    model = Prophet()
    model.fit(history_df)
    future = model.make_future_dataframe(periods=7)
    forecast = model.predict(future)
    return forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(7).reset_index(drop=True)


# A small Q-learning agent to recommend actions based on soil moisture forecast + rainfall
class SimpleQAgent:
    def __init__(self, alpha=0.3, gamma=0.9, eps=0.1):
        # state: (soil_level_bucket, rainfall_bucket) -> action: irrigate / wait / fertilize
        self.alpha = alpha
        self.gamma = gamma
        self.eps = eps
        self.actions = ['irrigate', 'wait', 'fertilize']
        self.q = {}  # dict of state -> action values

    def _state_key(self, soil, rain):
        # discretize
        soil_b = min(4, int(soil // 10))  # 0..4
        rain_b = 0 if rain < 2 else (1 if rain < 6 else 2)
        return (soil_b, rain_b)

    def get_action(self, soil, rain):
        s = self._state_key(soil, rain)
        if random.random() < self.eps or s not in self.q:
            return random.choice(self.actions)
        vals = self.q.get(s, {a:0 for a in self.actions})
        return max(vals, key=vals.get)

    def update(self, soil, rain, action, reward, next_soil, next_rain):
        s = self._state_key(soil, rain)
        ns = self._state_key(next_soil, next_rain)
        self.q.setdefault(s, {a:0 for a in self.actions})
        self.q.setdefault(ns, {a:0 for a in self.actions})
        old = self.q[s][action]
        future = max(self.q[ns].values())
        self.q[s][action] = old + self.alpha * (reward + self.gamma * future - old)


import os
AGENT_PATH = os.path.join(os.path.dirname(__file__), 'q_agent.pkl')

def _load_agent():
    if os.path.exists(AGENT_PATH):
        try:
            with open(AGENT_PATH, 'rb') as f:
                return pickle.load(f)
        except Exception:
            pass
    return SimpleQAgent()

def _save_agent(agent):
    try:
        with open(AGENT_PATH, 'wb') as f:
            pickle.dump(agent, f)
    except Exception:
        pass


def generate_recommendations(forecast_df, recent_weather=None):
    """Generate recommendations using a simple learned Q-policy over forecasted soil moisture and recent rainfall.
    The function returns a list of recommendations (one per forecast day) and a short explanation.
    """
    agent = _load_agent()
    recs = []
    # If recent_weather missing, assume no rain
    recent_rain = recent_weather.get('rainfall', 0) if recent_weather else 0
    # For each forecast day decide action
    for idx, row in forecast_df.iterrows():
        soil_pred = float(row['yhat'])
        rain_pred = recent_rain  # simplistic: use recent rain as proxy
        action = agent.get_action(soil_pred, rain_pred)
        # simple heuristic reward simulation: if soil low and irrigate -> +1, if soil high and irrigate -> -1
        reward = 0
        if soil_pred < 35 and action == 'irrigate':
            reward = 1.0
        if soil_pred > 60 and action == 'irrigate':
            reward = -1.0
        if action == 'fertilize' and soil_pred < 40:
            reward = 0.5
        # simulate a next state (very rough): irrigation raises soil by 5, rain adds 3
        next_soil = soil_pred + (5 if action == 'irrigate' else 0) + (3 if rain_pred > 1 else 0)
        next_rain = max(0, rain_pred - 1)
        agent.update(soil_pred, rain_pred, action, reward, next_soil, next_rain)
        recs.append({
            'day': int(idx)+1,
            'pred_soil': round(soil_pred,1),
            'action': action,
            'confidence': round(abs(reward),2)
        })
    _save_agent(agent)
    explanation = "Recommendations generated by a lightweight Q-learning agent using forecasted soil moisture and recent rainfall."
    return recs, explanation
